setwd("~/NationalEnv")
library(tidyverse); library(GWASpoly)
source(file = "ascer.fn.R")
source(file = "newReadGWASpoly.fn.R")
chipPhenoSelected <- read_csv("chipPhenoSelected.csv")
chipGenoSelected <- read_csv("chipGenoSelected.csv")
wisconsinChips <- chipPhenoSelected %>% 
  select(variety, sel.site, trial) %>%
  mutate(sel.site = ifelse(sel.site == "Wisconsin", 1, 0))
data <- read.GWASpoly.object(ploidy = 4, phenos = wisconsinChips, genos = chipGenoSelected, n.traits = 1, format = "numeric")
data.original <- set.K(data, LOCO=FALSE)
params <- set.params(geno.freq  = 1 - (10/605))
data.original.scan <- GWASpoly(data.original,models=c("additive"),traits=c("sel.site"),params=params)
data.LOCO <- set.K(data, LOCO=TRUE)
data.LOCO.scan <- GWASpoly(data.original,models=c("additive"),traits=c("sel.site"),params=params)
save(data.original.scan, data.LOCO.scan, file = "wisconsinGWAS.RData")